# Used hello_world template, but renamed to generate_image
# Created new role and policy, and increased timeout and memory, due to timeout error when invoking the generate image function.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_generator_60

  Sample SAM Template for sam_generator_60

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024

Resources:
  GenerateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: generate_image/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Role: arn:aws:iam::244530008913:role/GenerateImageFunction_role_cand60
      Events:
        GenerateImage:
          Type: Api
          Properties:
            Path: /generate
            Method: post
      Environment:
        Variables:
          BUCKET_NAME: pgr301-couch-explorers

Outputs:
  GenerateImageApi:
    Description: "API Gateway endpoint URL for Prod stage for GenerateImageFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate/"
  GenerateImageFunction:
    Description: "Generate Image Lambda Function ARN"
    Value: !GetAtt GenerateImageFunction.Arn
  GenerateImageFunctionIamRole:
    Description: "Explicit IAM Role created for GenerateImageFunction"
    Value: arn:aws:iam::244530008913:role/GenerateImageFunction_role_cand60
