#Used hello_world template, but renamed to generate_image
#Created new role and policy
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam_generator_60

  Sample SAM Template for sam_generator_60

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  GenerateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: GenerateImage/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Role: arn:aws:iam::244530008913:role/GenerateImageFunction_role_cand60  # Specify role here
      Events:
        GenerateImage:
          Type: Api
          Properties:
            Path: /generate
            Method: get

Outputs:
  GenerateImageApi:
    Description: "API Gateway endpoint URL for Prod stage for GenerateImageFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/generate/"  # Updated URL
  GenerateImageFunction:
    Description: "Generate Image Lambda Function ARN"
    Value: !GetAtt GenerateImageFunction.Arn
  GenerateImageFunctionIamRole:
    Description: "Explicit IAM Role created for GenerateImageFunction"
    Value: arn:aws:iam::244530008913:role/GenerateImageFunction_role_cand60
