name: "Docker Publish Workflow"

on:
  push:
    branches:
      - main
#    paths:
 #     - 'java_sqs_client/**'

defaults:
  run:
    working-directory: ./java_sqs_client

jobs:
  build-and-publish:
    name: "Build and Publish Docker Image"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Set up Docker Build"
        uses: docker/setup-buildx-action@v2

      - name: "Log in to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: "Extract Git Tag or Default to Latest"
        id: extract_tag
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
          else
            TAG="latest"
          fi
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: "Build Docker Image"
        run: |
          docker build . -t ${{ secrets.DOCKER_HUB_USERNAME }}/java-sqs-client:${{ env.TAG }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/java-sqs-client:latest

      - name: "Push Docker Image to Docker Hub"
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/java-sqs-client:${{ env.TAG }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/java-sqs-client:latest
