on:
  push:
    branches:
      - main
    paths:
      - 'sam_lambda/**'

defaults:
  run:
    working-directory: ./sam_lambda/sam_generator_60

jobs:
  deploy-sam-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1 
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name sam-generator-60-stack --s3-bucket pgr301-couch-explorers --capabilities CAPABILITY_IAM --region eu-west-1
