name: "Terraform Deploy Workflow"

on:
  push:
    branches:
      - '**'
    paths:
      - 'infra/**'

jobs:
  terraform:
    name: "Terraform Deployment Job"
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-1
    defaults:
      run:
        working-directory: ./infra
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Debug - List Infra Directory Contents"
        run: ls -la ./infra

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2

      - name: "Initialize Terraform"
        run: terraform init

      - name: "Terraform Plan"
        if: github.ref != 'refs/heads/main'
        run: terraform plan -var-file="./terraform.tfvars"

      - name: "Terraform Apply"
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file="./terraform.tfvars"
